name: tests

on:
  push:

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Report Swift version
        run: swift --version
      - name: Run macOS tests
        run: |
          swift test --enable-code-coverage
