name: tests

on:
  push:

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2.3.0
        with:
          swift-version: '6.0'
      - name: Run macOS tests
        run: |
          swift test --enable-code-coverage
